server:
  port: 8080

spring:
  application:
    name: cloud-drive
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_drive?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1215225@Hlk
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true
        use_sql_comments: true
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 1319209732@qq.com
    password: ljgwpspveouofejh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Redisson配置
redisson:
  config:
    singleServerConfig:
      address: "redis://localhost:6379"
      database: 0
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      password: null
      subscriptionsPerConnection: 5
      clientName: null
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      connectionMinimumIdleSize: 10
      connectionPoolSize: 64
      dnsMonitoringInterval: 5000

# Sa-Token配置
sa-token:
  # token名称
  token-name: Authorization
  # token有效期
  timeout: 2592000
  # token临时有效期
  active-timeout: -1
  # 是否允许同一账号并发登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否尝试从请求体里读取token
  is-read-body: true
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: true
  # token前缀
  token-prefix: ""
  # 使用 Redis Jackson DAO 存储 Sa-Token 数据
  dao: redisJackson

# OSS配置
oss:
  enabled: true
  access-key-id: ${ALIYUN_ACCESS_KEY_ID}
  access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucket-name: oss-bucket-helukun-001

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
